[build]
  base = "."
  command = "npm install && npm run build"
  publish = "my-project/dist"

[functions]
  directory = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
