[build]
  base    = "my-project"
  command = "npm install && npm run build"
  publish = "dist"

[functions]
  directory = "../backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
